import type { Metadata } from "next";
import { NavBar } from "@/components/nav-bar";
import { LayoutShell } from "@/components/layout-shell";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "MovieAI",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LayoutShell navBar={<NavBar />}>{children}</LayoutShell>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
